=== giacomoRanieri/PD2-2016-Assigment-1/dtd/nffgInfo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT nffgInfo (nffgs)>
<!ELEMENT nffgs ((nffg)*)>

<!ELEMENT nffg (updateTime, nodes, policies)>
<!ATTLIST nffg 
	name ID #REQUIRED >

<!ELEMENT updateTime (#PCDATA)>
<!ELEMENT nodes ((node)*)>

<!ELEMENT node (funcType, links)>
<!ATTLIST node 
	name ID #REQUIRED >

<!ELEMENT policies ((reachabilityPolicy)*, (traversalPolicy)*)>

<!ELEMENT reachabilityPolicy (((verificationResult)?), (sourceNode, destinationNode))>
<!ATTLIST reachabilityPolicy
	positive NMTOKEN #REQUIRED
	name ID #REQUIRED >

<!ELEMENT traversalPolicy ((((verificationResult)?), (sourceNode, destinationNode)), (traversedFunctionalTypes))>
<!ATTLIST traversalPolicy
	positive NMTOKEN #REQUIRED
	name ID #REQUIRED >

<!ELEMENT funcType (#PCDATA)>
<!ELEMENT links ((link)*)>

<!ELEMENT link (destinationNode)>
<!ATTLIST link 
	name ID #REQUIRED >
	
<!ELEMENT destinationNode EMPTY>
<!ATTLIST destinationNode 
	name IDREF #REQUIRED >
	
<!ELEMENT verificationResult ANY>

<!ELEMENT sourceNode EMPTY>
<!ATTLIST sourceNode 
	name IDREF #REQUIRED >
	
<!ELEMENT traversedFunctionalTypes ((funcType)*)>
<!ELEMENT verificationResultMsg (#PCDATA)>
<!ELEMENT verificationTime (#PCDATA)>

=== giacomoRanieri/PD2-2016-Assigment-1/dtd/nffgInfo.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE nffgInfo SYSTEM "nffgInfo.dtd">
<nffgInfo>
    <nffgs>
        <nffg name="fg1">
            <updateTime>2016-11-21T16:00:00</updateTime>
            <nodes>
                <node name="node1.1">
                    <funcType>WEB_CLIENT</funcType>
                    <links>
                        <link name="CtoS1">
                            <destinationNode name="node1.3" />
                        </link>
                    </links>
                </node>
                <node name="node1.2">
                    <funcType>WEB_SERVER</funcType>
                    <links>
                        <link name="StoC1">
                            <destinationNode name="node1.3" />
                        </link>
                    </links>
                </node>
                <node name="node1.3">
                    <funcType>FW</funcType>
                    <links>
                        <link name="StoFtoC1">
                            <destinationNode name="node1.1" />
                        </link>
                        <link name="CtoFtoS1">
                            <destinationNode name="node1.2" />
                        </link>
                    </links>
                </node>
            </nodes>
            <policies>
                <traversalPolicy name="noNAT" positive="false">
                    <sourceNode name="node1.1"/>
                    <destinationNode name="node1.2"/>
                    <traversedFunctionalTypes>
                    	<funcType>NAT</funcType>
                    </traversedFunctionalTypes>
                </traversalPolicy>
            </policies>
        </nffg>
        <nffg name="fg2">
            <updateTime>2016-11-21T16:00:00</updateTime>
            <nodes>
                <node name="node2.1">
                    <funcType>WEB_CLIENT</funcType>
                    <links>
                        <link name="CtoS2">
                            <destinationNode name="node2.3" />
                        </link>
                    </links>
                </node>
                <node name="node2.2">
                    <funcType>WEB_SERVER</funcType>
                    <links>
                        <link name="StoC2">
                            <destinationNode name="node2.3" />
                        </link>
                    </links>
                </node>
                <node name="node2.3">
                    <funcType>FW</funcType>
                    <links>
                        <link name="StoFtoC2">
                            <destinationNode name="node2.1" />
                        </link>
                        <link name="CtoFtoS2">
                            <destinationNode name="node2.2" />
                        </link>
                    </links>
                </node>
            </nodes>
            <policies>
                <reachabilityPolicy name="ClientReacheServer" positive="true">
                    <sourceNode name="node2.1"/>
                    <destinationNode name="node2.2"/>
                </reachabilityPolicy>
            </policies>
        </nffg>
    </nffgs>
</nffgInfo>
