=== giacomoRanieri/PD2-2016-Assigment-1/xsd/nffgInfo2.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML 2016 Designer Edition (Trial) 14.1.5.6733 (https://www.liquid-technologies.com)-->
<schema xmlns:tns="http://www.example.org/nffgInfo" elementFormDefault="qualified" targetNamespace="http://www.example.org/nffgInfo" xmlns="http://www.w3.org/2001/XMLSchema">
    <element name="networkDefinition" type="tns:NetworkDefinitionType">
        <key name="nffgId">
            <selector xpath="nffg" />
            <field xpath="@name" />
        </key>
        <!-- <keyref name="nffgRef" refer="tns:nffgId"> <selector xpath="polycies/policy/nffg" 
			/> <field xpath="@name" /> </keyref> <key name="nffgNode"> <selector xpath="nffgs" 
			/> <field xpath="nffg/@name" /> <field xpath="nodes/node/@name" /> </key> 
			<keyref name="nffgNodeReachDestRef" refer="tns:nffgNode"> <selector xpath="polycies/reachabilityPolicy/nffg" 
			/> <field xpath="@name" /> <field xpath="destinationNode/@name" /> </keyref> 
			<keyref name="nffgNodeTraversDestRef" refer="tns:nffgNode"> <selector xpath="polycies/traversalPolicy/nffg" 
			/> <field xpath="@name" /> <field xpath="destinationNode/@name" /> </keyref> 
			<keyref name="nffgNodeReachSourceRef" refer="tns:nffgNode"> <selector xpath="polycies/reachabilityPolicy/nffg" 
			/> <field xpath="@name" /> <field xpath="destinationNode/@name" /> </keyref> 
			<keyref name="nffgNodeTraverSourceRef" refer="tns:nffgNode"> <selector xpath="polycies/traversalPolicy/nffg" 
			/> <field xpath="@name" /> <field xpath="destinationNode/@name" /> </keyref> -->
    </element>
    <complexType name="NetworkDefinitionType">
        <sequence>
            <element name="nffg" type="tns:nffgType" minOccurs="0" maxOccurs="unbounded">
                <key name="nodeId">
                    <selector xpath="nodes/node" />
                    <field xpath="@name" />
                </key>
                <keyref name="destRef" refer="tns:nodeId">
                    <selector xpath="links/link/destinationNode" />
                    <field xpath="@name" />
                </keyref>
                <keyref name="sourceRef" refer="tns:nodeId">
                    <selector xpath="links/link/sourceNode" />
                    <field xpath="@name" />
                </keyref>
            </element>
        </sequence>
    </complexType>
    <complexType name="baseType">
        <attribute name="name" type="string" use="required" />
    </complexType>
    <complexType name="nffgType">
        <complexContent>
            <extension base="tns:baseType">
                <sequence>
                    <element name="updateTime" type="dateTime" minOccurs="1" />
                    <element name="nodes">
                        <complexType>
                            <sequence>
                                <element name="node" type="tns:nodeType" minOccurs="0" maxOccurs="unbounded" />
                            </sequence>
                        </complexType>
                        <!-- TODO: unique node name -->
                    </element>
                    <element name="links">
                        <complexType>
                            <sequence>
                                <element name="link" type="tns:linkType" minOccurs="0" maxOccurs="unbounded" />
                            </sequence>
                        </complexType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="nodeType">
        <complexContent>
            <extension base="tns:baseType">
                <sequence>
                    <element name="funcType" type="tns:FunctionalType" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="linkType">
        <complexContent>
            <extension base="tns:baseType">
                <sequence>
                    <group ref="tns:sourcedest" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="policyType">
        <complexContent>
            <extension base="tns:baseType">
                <sequence>
                    <element name="nffg" minOccurs="1" />
                    <element name="verificationResult" type="tns:verificationResultType" minOccurs="0" />
                </sequence>
                <attribute name="positive" type="boolean" use="required" />
            </extension>
        </complexContent>
    </complexType>
    <complexType name="reachabilityPolicyType">
        <complexContent>
            <extension base="tns:policyType">
                <sequence>
                    <group ref="tns:sourcedest" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="TraversalPolicyType">
        <complexContent>
            <extension base="tns:reachabilityPolicyType">
                <sequence>
                    <element name="traversedFunctionalTypes">
                        <simpleType>
                            <list itemType="tns:FunctionalType" />
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <simpleType name="FunctionalType" final="restriction">
        <restriction base="string">
            <enumeration value="FW" />
            <enumeration value="DPI" />
            <enumeration value="NAT" />
            <enumeration value="SPAM" />
            <enumeration value="CACHE" />
            <enumeration value="VPN" />
            <enumeration value="WEB_SERVER" />
            <enumeration value="WEB_CLIENT" />
            <enumeration value="MAIL_SERVER" />
            <enumeration value="MAIL_CLIENT" />
        </restriction>
    </simpleType>
    <complexType name="verificationResultType">
        <sequence>
            <element name="verificationResult" type="boolean" />
            <element name="verificationResultMsg" type="string" />
            <element name="verificationTime" type="dateTime" />
        </sequence>
    </complexType>
    <group name="sourcedest">
        <sequence>
            <element name="destinationNode" minOccurs="1" />
            <element name="sourceNode" minOccurs="1" />
        </sequence>
    </group>
</schema>

=== giacomoRanieri/PD2-2016-Assigment-1/xsd/nffgInfo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<networkDefinition xmlns="http://www.example.org/nffgInfo"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/nffgInfo nffgInfo2.xsd">
	<nffg name="fg1">
		<updateTime>2016-11-21T16:00:00</updateTime>
		<nodes>
			<node name="node1">
				<funcType>WEB_CLIENT</funcType>
			</node>
			<node name="node2">
				<funcType>WEB_SERVER</funcType>
			</node>
		</nodes>
		<links>
			<link name="StoC">
				<destinationNode name="node1" />
				<sourceNode name="node2" />
			</link>
			<link name="CtoS">
				<destinationNode name="node2" />
				<sourceNode name="node1" />
			</link>
		</links>
	</nffg>
	<nffg name="fg1">
		<updateTime>2016-11-21T16:00:00</updateTime>
		<nodes>
			<node name="node1">
				<funcType>WEB_CLIENT</funcType>
			</node>
			<node name="node2">
				<funcType>WEB_SERVER</funcType>
			</node>
		</nodes>
		<links>
			<link name="CtoS">
				<destinationNode name="node2" />
				<sourceNode name="node1" />
			</link>
			<link name="StoC">
				<destinationNode name="node1" />
				<sourceNode name="node2" />
			</link>
		</links>
	</nffg>
</networkDefinition>
